[versions]
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"

androidxActivity = "1.10.1"
androidxComposeBom = "2025.05.01"
material3-adaptive = "1.1.0"
material3-adaptive-navigation-suite = "1.3.2"
uiToolingPreview = "1.7.7"
wearCompose = "1.4.0"
androidxLifecycle = "2.9.0"
androidxLifecycleKMP = "2.8.4"
compose = "2.0.0"
materialIcon = "1.7.8"

material = "1.12.0"
appCompat = "1.7.0"
constraint = "2.2.1"
navFragment = "2.9.0"
navUi = "2.9.0"
livedata = "2.9.0"
multiplatformSettings = "0.8.1"
composeDestinations = "2.2.0"
coilAccompanist = "0.15.0"
pagerAccompanist = "0.15.0"
kermit = "1.1.3"
koin = "4.0.4"
coroutine = "1.10.1"
serialization = "1.8.1"
dateTime = "0.4.0"
ktor = "3.1.2"
lottie = "5.2.0"
shimmer = "1.0.2"
agp = "8.6.1"
skie = "0.10.0"
kmpViewModel = "1.0.0-BETA-11"
kmpNativeCoroutines = "1.0.0-ALPHA-38"
yamlkt = "0.12.0"
sqlDelight = "2.1.0"
room = "2.7.1"
androidGradlePlugin = "8.9.3"
gradleVersionsPlugin = "0.51.0"
sqlite = "2.5.1"

[libraries]
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "dateTime" }
kotlinx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "livedata" }

android-material = { module = "com.google.android.material:material", version.ref = "material" }

androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material-icon = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIcon" }
androidx-compose-material3 =  { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }
androidx-compose-material3-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "material3-adaptive" }
androidx-compose-material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "material3-adaptive" }
androidx-compose-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3-adaptive-navigation-suite" }

compose-lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "shimmer" }

accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "coilAccompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "pagerAccompanist" }

compose-destinations = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "composeDestinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestinations" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-json-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }

kermit-logger = { module = "co.touchlab:kermit", version.ref = "kermit" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
kmp-viewModel = { module = "com.rickclephas.kmp:kmp-observableviewmodel-core", version.ref = "kmpViewModel" }
kotlin-yaml = { module = "net.mamoe.yamlkt:yamlkt", version.ref = "yamlkt" }

sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqldelight-web-driver = { module = "app.cash.sqldelight:web-worker-driver", version.ref = "sqlDelight" }

androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
androidx-sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-ksp = { module = "androidx.room:room-compiler", version.ref = "room" }

[plugins]
gradleVersionsPlugin = { id = "com.github.ben-manes.versions", version.ref  = "gradleVersionsPlugin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose" }
kmp-nativecoroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "kmpNativeCoroutines" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
room = { id = "androidx.room", version.ref = "room" }